#!/bin/zsh

if [ "release" = "$1" ]; then
	clang -Ofast client.c -o client -lSDL2
	# clang -Ofast server.c -o server

elif [ "clean" = "$1" ]; then
	rm -rf client
	rm -rf client.dSYM
	rm -rf server
	rm -rf server.dSYM

elif [ "" = "$1" ]; then 
	clang -g -O0 -Weverything -Wno-poison-system-directories -Wno-padded -Wno-reserved-id-macro -fsanitize=address,undefined client.c -o client -lSDL2
	# clang -g -O0 -fsanitize=address,undefined server.c -o server
	echo unimplemented.

elif [ "client" = "$1" ]; then 
	clang -g -O0 -Weverything -Wno-poison-system-directories -Wno-padded -fsanitize=address,undefined client.c -o client -lSDL2
	
elif [ "server" = "$1" ]; then 
	# clang -g -O0 -Weverything -Wno-poison-system-directories -fsanitize=address,undefined server.c -o server
	echo unimplemented.

else 
	echo "build: unknown target: $1"
fi
