#!/bin/zsh 

# todo: remove the dependancy on the "xxd" program, my reading in the .metallib file manually programmatically. 

if [ "release" = "$1" ]; then
	clang++ -std=c++17 -Ofast -ferror-limit=2 -I ./libraries main.cpp libraries/MetalCPP.cpp -fsanitize=address,undefined `sdl2-config --cflags --libs` -framework Metal -framework QuartzCore -framework Foundation -o run 

elif [ "clean" = "$1" ]; then
	rm -rf run
	rm -rf run.dSYM

elif [ "metal" = "$1" ]; then
	../tools/file_splitter/form one ../tools/bin/metal ../tools/bin/metal_half0 ../tools/bin/metal_half1
	chmod 755 ../tools/bin/metal
	../tools/bin/metal -std=macos-metal2.2 triangle.metal -o triangle.metallib
	xxd -i triangle.metallib > triangle_metallib.h
	rm ../tools/bin/metal

elif [ "" = "$1" ]; then 

	../tools/file_splitter/form one ../tools/bin/metal ../tools/bin/metal_half0 ../tools/bin/metal_half1
	chmod 755 ../tools/bin/metal
	../tools/bin/metal -std=macos-metal2.2 triangle.metal -o triangle.metallib
	xxd -i triangle.metallib > triangle_metallib.h
	rm ../tools/bin/metal

	clang++ -g -std=c++17 -O2 -ferror-limit=2 -I ./libraries main.cpp libraries/MetalCPP.cpp -fsanitize=address,undefined `sdl2-config --cflags --libs` -framework Metal -framework QuartzCore -framework Foundation -o run 

else 
	echo "build: unknown target: $1"
fi
















	# clang -Ofast c.c -o editor

	# clang -g -O0 -Weverything -Wno-declaration-after-statement -fsanitize=address,undefined c.c -o editor -ferror-limit=4



