# makefile for the 256 game. written by daniel rehman, on 2008296.215814.

server: source/server/server/main.c
	gcc -O3 -o server source/server/server/main.c



#
#client: source/client/client/main.c
#	gcc -O3 -o client source/client/client/main.c
#
